#!/usr/bin/env python3

print('importing main from Python package verotest in vero_node1')
from verotest import main
print('imported main from Python package verotest in vero_node1')

if __name__ == '__main__':
	print("executing main() in vero_node1")
	main()

